spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: comsc
    url: jdbc:mariadb://localhost:3306/assessmenttracking
  main:
    allow-bean-definition-overriding: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: madhanmonishj@gmail.com
    password: caan sgoq ktgf hxed
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
  typeAliasesPackage: com.assessment.comsc.entity
